server:
  port: 8090
spring:
  datasource:
    username: root
    password: faber@2022
    url: jdbc:mysql://localhost:3306/microservice-cards
  jpa:
    properties:
      hibernate:
        dialect:
    hibernate:
      ddl-auto: update
