server:
  port: 9000
spring:
  datasource:
    username: root
    password: faber@2022
    url: jdbc:mysql://localhost:3306/microservice-loans
  jpa:
    properties:
      hibernate:
        dialect:
    hibernate:
      ddl-auto: update
